name: Hello world!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Current date
        run: |
          date
      - name: List directory files
        run: |
          ls -la
