name: Deployment pipeline

env:
  SKIPPED_COMMIT: ${{contains(toJson(github.event.commits.*.message),'#skip')}}
  PUSH_MAIN: ${{github.event_name == 'push'}}
  NEW_TAG_RESELASE: ${{(contains(toJson(github.event.commits.*.message),'#skip') == 'false') && (github.event_name == 'push')}}
  NOT_SKIPPED: ${{(contains(toJson(github.event.commits.*.message),'#skip') == 'false')}}
  CONTAINS: ${{contains('something','some') == 'true'}}
  CONTAINS_2: ${{contains('something','some')}}
  NOT_CONTAINS: ${{contains('something','some')}}
  NOT_CONTAINS_2: ${{contains('something','some')== 'false'}}
  SEVERAL_CONDITIONS: ${{contains('something','some') && 2>1 }}
on:
  push:
    branches:
      - main
      - new-branch
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  debug_info:
    runs-on: ubuntu-22.04
    steps:
      - name: condition new tag release
        run: echo ${{env.NEW_TAG_RESELASE}}

      - name: event name
        run: echo ${{toJson(github.event_name)}}

      - if: ${{env.PUSH_MAIN && env.SKIPPED_COMMIT == 'false'}}
        name: push && not skipped
        run: echo "another testing works ${{env.PUSH_MAIN}}, ${{env.SKIPPED_COMMIT}}, ${{env.PUSH_MAIN && env.SKIPPED_COMMIT}}"
  #
  tag_release:
    if: ${{github.env.PUSH_MAIN && github.env.SKIPPED_COMMIT == 'false'}}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "actions/checkout@v4"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BUMP: patch
