name: Deployment pipeline

env:
  SKIPPED_COMMIT: ${{contains(toJson(github.event.commits.*.message),'#skip')}}
<<<<<<< HEAD
  PUSH_MAIN: ${{github.event_name == 'push'}}
  NEW_TAG_RESELASE: ${{(contains(toJson(github.event.commits.*.message),'#skip') == 'false') && (github.event_name == 'push')}}

=======
  PUSH_EVENT: ${{github.event_name == 'push'}}
>>>>>>> 448bd6d (github data)
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
<<<<<<< HEAD
jobs:
  debug_info:
    runs-on: ubuntu-22.04
    steps:
      - name: condition new tag release
        run: echo ${{env.NEW_TAG_RESELASE}}
      - name: event name
        run: echo ${{toJson(github.event_name)}}

  tag_release:
    if: ${{ github.env.NEW_TAG_RESELASE == 'true' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "actions/checkout@v4"

=======

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: "npm run test:unit"

      #     - name: Install Playwright Browsers
      #       run: npx playwright install --with-deps

      #     - name: E2E Tests
      #       run: npm run test:e2e

      #     - uses: actions/upload-artifact@v4
      #       if: ${{ !cancelled() }}
      #       with:
      #         name: playwright-report
      #         path: playwright-report/
      #         retention-days: 30

      - name: Trigger deployment
        if: ${{ env.PUSH_EVENT == 'true' }}
        run: curl ${{secrets.RENDER_DEPLOY_HOOK}}

  debug_info:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: github event_name
        run: echo ${{toJson(github.event_name)}}
      - name: github action
        run: echo ${{toJson(github.action)}}
      - name: github
        run: echo ${{toJson(github)}}

  tag_release:
    if: ${{ 1>2 && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "actions/checkout@v4"

>>>>>>> 448bd6d (github data)
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BUMP: patch
<<<<<<< HEAD
=======
#

>>>>>>> 448bd6d (github data)
