name: Deployment pipeline

env:
  SKIPPED_COMMIT: ${{contains(toJson(github.event.commits.*.message),'#skip')}}
  PUSH_MAIN: ${{github.event_name == 'push'}}
  NEW_TAG_RESELASE: ${{(contains(toJson(github.event.commits.*.message),'#skip') == 'false') && (github.event_name == 'push')}}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  debug_info:
    runs-on: ubuntu-22.04
    steps:
      - name: condition new tag release
        run: echo ${{env.NEW_TAG_RESELASE}}
      - name: event name
        run: echo ${{toJson(github.event_name)}}

  tag_release:
    if: ${{ github.env.NEW_TAG_RESELASE == 'true' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "actions/checkout@v4"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BUMP: patch
