name: Deployment pipeline

env:
  SKIPPED_COMMIT: ${{contains(toJson(github.event.commits.*.message),'#skip')}}
  PUSH_EVENT: ${{github.event_name == 'push'}}
  NEW_TAG_RESELASE: ${{(contains(toJson(github.event.commits.*.message),'#skip') == 'false') && (github.event_name == 'push')}}
  NOT_SKIPPED: ${{(!contains(toJson(github.event.commits.*.message),'#skip'))}}
  CONTAINS: ${{contains('something','some') == 'true'}}
  CONTAINS_2: ${{contains('something','some')}}
  NOT_CONTAINS: ${{!contains('something','asd')}}
  NOT_CONTAINS_2: ${{contains('something','asd')== 'false'}}
  SEVERAL_CONDITIONS: ${{contains('something','some') && 2>1 }}
#
on:
  push:
    branches:
      - main
      - new-branch
  # pull_request:
  #   branches: [main]
  #   types: [opened, synchronize]

jobs:
  # simple_deployment_pipeline:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Check style
  #       run: npm run eslint

  #     - name: Build
  #       run: npm run build

  #     # - name: Start
  #     #   run: npm run start-prod

  #     - name: Unit Tests
  #       run: "npm run test:unit"

  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps

  #     - name: E2E Tests
  #       run: npm run test:e2e

  #     - uses: actions/upload-artifact@v4
  #       if: ${{ !cancelled() }}
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30

  # - name: Trigger deployment
  #   if: ${{ github.event_name == 'push' }}
  #   run: curl ${{secrets.RENDER_DEPLOY_HOOK}}

  debug_info:
    if: ${{github.env.SKIPPED_COMMIT == 'false'}}
    runs-on: ubuntu-22.04
    steps:
      - name: condition new tag release
        run: echo ${{env.NEW_TAG_RESELASE}}
      - name: event name
        run: echo ${{toJson(github.event_name)}}
      - if: ${{env.PUSH_EVENT && env.SKIPPED_COMMIT == 'false'}}
        name: push && not skipped
        run: echo "another testing works ${{env.PUSH_EVENT}}, ${{env.SKIPPED_COMMIT == 'false'}}, ${{env.PUSH_EVENT && env.SKIPPED_COMMIT == 'false'}}"

  tag_release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: condition check
        run: echo "${{env}}"

      - if: ${{env.NOT_SKIPPED == 'true'}}
        name: tag release 1
        run: echo "tag-releasing- not skipped"
      - if: ${{env.SKIPPED_COMMIT == 'true'}}
        name: tag release skipped 1
        run: echo "tag skipped"
      - if: ${{env.SKIPPED_COMMIT}}
        name: tag release skipped 2
        run: echo "tag skipped 2 ${{env.SKIPPED_COMMIT}}"
      - if: env.SKIPPED_COMMIT
        name: tag release skipped 3
        run: echo "tag skipped 3 ${{env.SKIPPED_COMMIT}}"
      - if: env.SKIPPED_COMMIT == 'true' && env.PUSH_EVENT == 'true'
        name: tag release skipped 4
        run: echo "tag skipped 4 ${{env.SKIPPED_COMMIT}}"
#
