name: Testing stuff

env:
  GITHUB_CONTEXT: ${{ github }}

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        run: echo "${{toJson(env.GITHUB_CONTEXT)}}"

      - name: commit message
        env:
          MESSAGE: ${{ toJson(github.event.commits.message) }}
        run: echo "$MESSAGE"
