name: Testing stuff

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  COMMIT_MESSAGE: ${{toJson(github.event.commits.*.message)}}
  SKIPPED_COMMIT: ${{contains(toJson(github.event.commits.*.message),'#skip')}}
  TRUE_CONDITION: ${{'true'}}
on:
  push:
    branches:
      - main
      - feature

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      # - name: condition check
      # run: echo "${{env.SKIPPED_COMMIT}}"

      - name: Test
        run: exit 1

      # - name: Test success
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     severity: info
      #     details: Test Succeeded!
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Discord Webhook Action on fail
        uses: tsickert/discord-webhook@v5.3.0
        if: failure()
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-color: 14701393
          embed-title: ❌ Test failed
          embed-description: This is a test that has failed
          # content: "Test failed"

      - name: Discord Webhook Action on succeed
        uses: tsickert/discord-webhook@v5.3.0
        if: success()
        with:
          embed-color: 6144854
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: ✅ Test succeed
          embed-description: This is a test that has succeeded
          # content: "Test succeded"

      # - name: Test Failure
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   if: failure()
      #   with:
      #     severity: error
      #     details: Test Failed!
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
