name: Testing stuff

env:
  GITHUB_CONTEXT: ${{ github }}
  # COMMIT_MESSAGES: ${{github.event.commits.message}}
  # SKIP_COMMIT: ${{contains(github.env.COMMIT_MESSAGES,'#skip')}}

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        run: echo "${{toJson(env.GITHUB_CONTEXT)}}"

      - name: commit message
        env:
          MESSAGE: ${{ toJson(github.event.commits.message) }}
        run: echo "$MESSAGE"

      # - if: ${{ github.env.SKIP_COMMIT == 'true' }}
      #   name: skip commit test
      #   run: echo "skipping commit"

      # - if: ${{ github.env.SKIP_COMMIT == 'false' }}
      #   name: NOT skipping commit test
      #   run: echo "not skipping commit"
