name: Testing stuff

env:
  COMMIT_MESSAGES: ${{toJson(github.event.commits.*.message)}}
  SKIP_COMMIT: ${{contains(github.env.COMMIT_MESSAGES,'#skip')}}

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ github }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        run: echo "${{github.env.COMMIT_MESSAGES}}"

      - if: ${{ github.env.SKIP_COMMIT == 'true' }}
        name: skip commit test
        run: echo "skipping commit"

      - if: ${{ github.env.SKIP_COMMIT == 'false' }}
        name: NOT skipping commit test
        run: echo "not skipping commit"
