name: Testing stuff

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  COMMIT_MESSAGE: ${{toJson(github.event.commits.*.message)}}
  SKIPPED_COMMIT: ${{contains(toJson(github.event.commits.*.message),'#skip')}}
  TRUE_CONDITION: ${{'true'}}
on:
  push:
    branches:
      - main
      - feature

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      # - name: condition check
      # run: echo "${{env.SKIPPED_COMMIT}}"

      - name: Test
        run: echo ${{github}} && exit 0

      # - name: Test success
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     severity: info
      #     details: Test Succeeded!
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Discord Webhook Action on fail
        uses: tsickert/discord-webhook@v5.3.0
        if: failure()
        with:
          embed-color: 14701393
          username: Github Actions
          avatar-url: https://avatars.githubusercontent.com/u/9919?v=4
          embed-title: ❌  Test failed
          embed-description: "This is a test that has failed \nis this the second line??"
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          # content: "Test failed"

      - name: Discord Webhook Action on succeed
        uses: tsickert/discord-webhook@v5.3.0
        if: success()
        with:
          username: Github Actions
          avatar-url: https://avatars.githubusercontent.com/u/9919?v=4
          embed-color: 6144854
          embed-title: ✅  Test succeed
          embed-description: This is a test that has succeeded \n is this *second* line?
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
