name: Testing stuff

env:
COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
SKIP_COMMIT: ${{contains($COMMIT_MESSAGES,'#skip')}}

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
        #   COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: skip commit test
        if: ${{ github.env.SKIP_COMMIT == 'true' }}
        run: echo "skipping commit"
        if: ${{ github.env.SKIP_COMMIT == 'false' }}
        run: echo "not skipping commit"
