name: Testing stuff

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  COMMIT_MESSAGE: ${{toJson(github.event.commits.*.message)}}
  SKIPPED_COMMIT: ${{contains(toJson(github.event.commits.*.message),'#skip')}}
on:
  push:
    branches:
      - main
      - new-branch

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: condition check
        run: echo "${{env.SKIPPED_COMMIT}}"
      #
      - if: ${{ env.SKIPPED_COMMIT == 'true' }}
        name: skip commit test
        run: echo "skipping commit- ${{env.COMMIT_MESSAGE}}"

      - if: ${{ env.SKIPPED_COMMIT == 'false' }}
        name: NOT skipping commit test
        run: echo "not skipping - ${{env.COMMIT_MESSAGE}}"
